---

  - name: XL Deploy | Install dependencies
    apt: pkg="{{item}}" state="installed"
    with_items:
       - acl
       - unzip
    become: yes
    tags:
      xl-deploy

  - name: XL Deploy | Ensure server dir exists
    file: path="{{xl_server_install_dir}}" state="directory" owner="{{xl_user}}" group="{{xl_user}}"
    become: yes
    tags:
      xl-deploy

  - name: XL Deploy | download server package
    get_url:
      url="{{xl_server_zip_pack}}"
      dest="/tmp/xl_server_pack.zip"
    tags:
      xl-deploy

  - name: XL Deploy | download cli package
    get_url:
      url="{{xl_cli_zip_pack}}"
      dest="/tmp/xl_cli_pack.zip"
    tags:
      xl-deploy

  - name: XL Deploy | unpack server package
    unarchive:
      src: /tmp/xl_server_pack.zip
      dest: "{{xl_server_install_dir}}"
      remote_src: True
    become: yes
    become_user: "{{xl_user}}"
    tags:
      xl-deploy

  - name: XL Deploy | rename server folder to generic name
    shell: mv xl-deploy-*-server xl-deploy-server
    args:
      chdir: "{{xl_server_install_dir}}"
    tags:
      xl-deploy

  - name: XL Deploy | Deploy license file, if any
    copy: src="{{xl_license_file}}" dest="{{xl_server_install_dir}}/xl-deploy-server/conf/deployit-license.lic" owner="{{xl_user}}" group="{{xl_user}}"
    become: yes
    become_user: "{{xl_user}}"
    tags:
      xl-deploy

  - block:

    - name: XL Deploy | Install expect dependency for guided installation
      apt: pkg="expect" state="present"
      become: yes
      tags:
        xl-deploy

    - name: XL Deploy | Template expect scripts
      template: src="{{role_dir}}/templates/{{item}}.j2" dest="{{xl_server_install_dir}}/xl-deploy-server/bin/{{item}}"
      with_items:
        - "{{xl_setup_mode}}_init.expect"
        - "{{xl_setup_mode}}_service.expect"

    - name: XL Deploy | Execute initial configuration
      shell: expect -f {{xl_setup_mode}}_init.expect
      args:
        chdir: "{{xl_server_install_dir}}/xl-deploy-server/bin"
      register: initial_config_result
      failed_when: "'Finished setup.' not in initial_config_result.stdout"
      tags:
        xl-deploy

    - name: XL Deploy | Execute service initialization
      shell: expect -f {{xl_setup_mode}}_service.expect
      args:
        chdir: "{{xl_server_install_dir}}/xl-deploy-server/bin"
      become: yes
      register: register_service_result
      failed_when: "'Service xl-deploy installed' not in register_service_result.stdout"
      when: docker_test is not defined
      tags:
        xl-deploy

    - name: XL Deploy | Drop automatic configuration scripts
      file: path="{{xl_server_install_dir}}/xl-deploy-server/bin/{{item}}" state="absent"
      with_items:
        - "{{xl_setup_mode}}_init.expect"
        - "{{xl_setup_mode}}_service.expect"
      become: yes
      tags:
        xl-deploy

    when: option_init_xl_server

  - name: XL Deploy | cli server dir exists
    file: path="{{xl_cli_install_dir}}" state="directory"
    tags:
      xl-deploy

  - name: XL Deploy | unpack cli package
    unarchive:
      src: /tmp/xl_cli_pack.zip
      dest: "{{xl_cli_install_dir}}"
      remote_src: True
    tags:
      xl-deploy

  - name: XL Deploy | rename cli folder to generic name
    shell: mv xl-deploy-*-cli xl-deploy-cli
    args:
      chdir: "{{xl_cli_install_dir}}"
    tags:
      xl-deploy

  - name: XL Deploy | init server
    shell: echo "{{xl_simple_init_sequence}}" | ./run.sh -setup
    args:
      chdir: "{{xl_server_install_dir}}/xl-deploy-server/bin"
    when: option_init_xl_server
    tags:
      xl-deploy
