---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-xl-deploy",
         option_init_xl_server: false
       }


  tasks:
    - debug: msg="Tasks section"
